// A primitive civ agent as a Primitive Function. Each turn the arena emails
// this address a briefing; this handler replies in thread with orders chosen
// by decide() in src/agent.mjs. Everything except the civ-specific part below
// comes from the Primitive "email-reply" Function template.
//
// env.PRIMITIVE_API_KEY, env.PRIMITIVE_WEBHOOK_SECRET, and
// env.PRIMITIVE_API_BASE_URL are auto-injected by the Primitive Functions runtime.
// Optional secret: ANTHROPIC_API_KEY (and MODEL) to let a model play.
//
// Imports are taken from the `/api` subpath, NOT the package root.
// The root export pulls in webhook signing helpers that depend on
// `node:crypto`, which breaks Workers-style bundles. The `/api`
// subpath is Workers-safe and exposes everything a handler needs,
// including Web Crypto signature verification.
import {
  createPrimitiveClient,
  isTrustedSender,
  normalizeReceivedEmail,
  PRIMITIVE_SIGNATURE_HEADER,
  type EmailReceivedEvent,
  verifyWebhookSignature,
  WebhookVerificationError,
} from "@primitivedotdev/sdk/api";
// @ts-expect-error plain ESM module
import { decide, onLetter } from "./src/agent.mjs";
// @ts-expect-error plain ESM module
import { DEFAULT_ARENA, civOfSender, extractLetters, kindOf, letterSubject, mailboxFor, parseGameBlock, parseGameOver, parseMailboxes, parseSubject } from "./src/game.mjs";

interface Env {
  PRIMITIVE_API_KEY: string;
  PRIMITIVE_API_BASE_URL: string;
  PRIMITIVE_WEBHOOK_SECRET: string;
  ANTHROPIC_API_KEY?: string;
  MODEL?: string;
  /** The arena's address; defaults to arena@primciv.com. */
  ARENA_ADDRESS?: string;
}

// What the harness remembers about each game, in Primitive memories under
// games/<game-id> (scoped to this Function).
interface GameState {
  game: string;
  civ?: string;
  arena?: string;
  mailboxes?: Record<string, string>;
  status?: "live" | "over";
  lastTurn?: number;
  outcome?: unknown;
  /** Letters received from rivals since the last turn, newest last (at most 10). */
  inbox?: Array<{ fromCiv: string; text: string; turn?: number }>;
  notes?: unknown;
}

// Loop-protection knob from the template: extra addresses this handler sends
// from, beyond the inbound recipient.
const EXTRA_SELF_ADDRESSES: string[] = [];

function extractEmailAddresses(value: string | null | undefined): string[] {
  return (
    value?.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)?.map((address) =>
      address.toLowerCase(),
    ) ?? []
  );
}

function domainPart(address: string): string | null {
  const at = address.lastIndexOf("@");
  return at === -1 ? null : address.slice(at + 1).toLowerCase();
}

function localPart(address: string): string {
  const at = address.lastIndexOf("@");
  return at === -1 ? address.toLowerCase() : address.slice(0, at).toLowerCase();
}

function inboundRecipientAddresses(event: EmailReceivedEvent): string[] {
  return [
    ...event.email.smtp.rcpt_to.flatMap(extractEmailAddresses),
    ...extractEmailAddresses(event.email.headers.to),
  ];
}

function inboundRecipientDomains(event: EmailReceivedEvent): Set<string> {
  return new Set(
    inboundRecipientAddresses(event)
      .map(domainPart)
      .filter((domain): domain is string => domain !== null),
  );
}

// Loop protection. A newly deployed Function starts as a fallback
// endpoint for managed domains and can receive bounces or auto-replies
// generated by its own outbound mail. Do not hardcode a managed suffix:
// staging, production, and custom domains all arrive through the same
// webhook shape. Derive the handler's inbound domains from the actual
// SMTP recipients instead.
//
// The default check skips:
//   - bounce notifications, which RFC 5321 requires to use an empty
//     SMTP envelope sender (MAIL FROM:<>). Replying to a null sender
//     is forbidden and would itself bounce, producing a
//     bounce-of-bounce chain. The body header on a bounce typically
//     reads "From: MAILER-DAEMON@..." which a naive From-only check
//     would treat as a normal sender, so we gate on the envelope here.
//   - direct self-mail where From equals one of the inbound recipients;
//   - mailer-daemon/postmaster bounces from the same domain as the
//     inbound, as a backup for bounces that arrive with a non-empty
//     envelope sender;
//   - any address explicitly listed in EXTRA_SELF_ADDRESSES.
//
// Anything with no identifiable sender at all (envelope + From both
// empty) is treated as a loop terminator: better to drop one ambiguous
// message than to reply blindly and loop on a bounce.
//
// Extend this helper if you need stricter detection. Common additions
// not implemented here today:
//   - Honor RFC 3834 auto-response headers: skip when an
//     auto-submitted header is anything other than "no", or when a
//     list-unsubscribe / precedence: bulk header is present. The
//     EmailReceivedEvent.email.headers shape does not currently surface
//     these, so detection requires either a parsed-headers field on
//     the event or a parse of the raw RFC 822 body.
//   - Track Message-ID / In-Reply-To chains to break ping-pong loops
//     between two cooperating handlers on different domains.
//   - Rate-limit replies per sender per hour as a safety net.
//
// Loop protection is NOT sender authentication. The address matching
// here is deliberately loose (it exists to avoid replying to our own
// mail, where a false positive just drops one reply). If your handler
// gates any privileged action on WHO sent the email, do not reuse this
// logic or regex the From header yourself; use isTrustedSender from
// "@primitivedotdev/sdk/api", which anchors the DMARC verdict to your
// expected domain and strict-parses the From header.
export function isLoop(event: EmailReceivedEvent): boolean {
  // RFC 5321: bounce notifications use the null MAIL FROM (envelope
  // sender = empty string). Some MTAs report this as "<>" verbatim.
  // Treat either as an unambiguous bounce signal.
  const envelopeSender = (event.email.smtp.mail_from || "").trim();
  if (envelopeSender === "" || envelopeSender === "<>") return true;

  const fromAddresses = [
    ...extractEmailAddresses(event.email.headers.from),
    ...extractEmailAddresses(event.email.smtp.mail_from),
  ];
  // No identifiable sender across either envelope or header: treat as
  // a loop terminator. Was return false in the original template; that
  // returned mail with empty headers straight back into the handler
  // and let bounces with malformed bodies slip past the bounce guard
  // above.
  if (fromAddresses.length === 0) return true;

  const inboundAddresses = new Set(inboundRecipientAddresses(event));
  const inboundDomains = inboundRecipientDomains(event);
  const extraSelfAddresses = new Set(
    EXTRA_SELF_ADDRESSES.map((address) => address.toLowerCase()),
  );

  for (const from of fromAddresses) {
    if (inboundAddresses.has(from)) return true;
    if (extraSelfAddresses.has(from)) return true;

    const fromDomain = domainPart(from);
    const fromLocal = localPart(from);
    const sameInboundDomain = fromDomain ? inboundDomains.has(fromDomain) : false;
    if (
      sameInboundDomain &&
      (fromLocal === "mailer-daemon" || fromLocal === "postmaster")
    ) {
      return true;
    }
  }

  return false;
}

// Is this mail authentically from `sender`? DMARC must pass and the From
// header must be exactly `sender`. Alignment is relaxed, as DMARC defines it:
// mail from civ@your-name.primitive.email authenticates as primitive.email,
// the organizational domain, so a subdomain of the DMARC domain counts.
function trustedSender(event: EmailReceivedEvent, sender: string): { trusted: boolean; reason: string } {
	const domain = domainPart(sender) ?? "";
	if (!domain) return { trusted: false, reason: "no sender domain" };
	const strict = isTrustedSender(event, { domain, sender });
	if (strict.trusted || strict.reason !== "dmarc-domain-mismatch") return { trusted: strict.trusted, reason: strict.reason };
	const dmarcDomain = String(event.email?.auth?.dmarcFromDomain ?? "").toLowerCase();
	if (!dmarcDomain || !domain.endsWith(`.${dmarcDomain}`)) return { trusted: false, reason: `dmarc domain ${dmarcDomain || "none"}` };
	const relaxed = isTrustedSender(event, { domain: dmarcDomain });
	// The organizational check fails only on the From domain; anything else
	// (auth failed, several From addresses) is a real rejection.
	if (!relaxed.trusted && relaxed.reason !== "from-domain-mismatch") return { trusted: false, reason: relaxed.reason };
	const from = extractEmailAddresses(event.email?.headers?.from)[0]?.toLowerCase() ?? "";
	return from === sender ? { trusted: true, reason: "trusted" } : { trusted: false, reason: "sender-mismatch" };
}

// Every ignored mail says why in `npm run logs`, so "my agent did not reply"
// is one command away from an answer.
function skip(reason: string): Response {
	console.log(`skipped: ${reason}`);
	return Response.json({ ok: true, skipped: reason });
}

export default {
  async fetch(
    req: Request,
    env: Env,
  ): Promise<Response> {
    try {
      const rawBody = await req.text();
      const signatureHeader = req.headers.get(PRIMITIVE_SIGNATURE_HEADER) ?? "";

      try {
        await verifyWebhookSignature({
          rawBody,
          signatureHeader,
          secret: env.PRIMITIVE_WEBHOOK_SECRET,
        });
      } catch (signatureError) {
        if (signatureError instanceof WebhookVerificationError) {
          return new Response("invalid signature", { status: 401 });
        }
        throw signatureError;
      }

      const event = JSON.parse(rawBody) as EmailReceivedEvent;

      // Only "email.received" exists today. Future event types will
      // arrive with a different discriminator; return 2xx so the
      // delivery loop does not burn its retry budget on payloads you
      // intentionally skipped.
      if (event.event !== "email.received") {
        return skip(event.event);
      }

      // Loop protection runs immediately after signature verification
      // and the event-type check. See isLoop above for what's covered
      // and how to extend it.
      if (isLoop(event)) {
        return skip("loop");
      }

      const client = createPrimitiveClient({
        apiKey: env.PRIMITIVE_API_KEY,
        apiBaseUrl: env.PRIMITIVE_API_BASE_URL,
      });

      const email = normalizeReceivedEmail(event);
      const kind = kindOf(email.subject);
      if (!kind || kind === "reply" || kind === "other") {
        return skip("not-civ-mail");
      }
      const { game } = parseSubject(email.subject);
      const arena = (env.ARENA_ADDRESS || DEFAULT_ARENA).toLowerCase();
      const self = inboundRecipientAddresses(event)[0] ?? "";
      const selfDomain = domainPart(self) ?? "";

      // Arena mail must really come from the arena (DMARC-authenticated as the
      // arena's domain and address). `npm run turn` sends from
      // arena-test@<your own domain>, which is trusted the same way.
      const fromArena =
        trustedSender(event, arena).trusted ||
        (selfDomain !== "" && trustedSender(event, `arena-test@${selfDomain}`).trusted);

      const key = `games/${game}`;
      const load = async (): Promise<GameState> => {
        try { return ((await client.memories.get(key)).value as unknown as GameState) ?? { game }; }
        catch { return { game }; }
      };
      const save = async (state: GameState) => {
        try { await client.memories.set({ key, value: state as never }); }
        catch (e) { console.error("memory save failed:", e); }
      };

      if (kind === "start" || kind === "over" || kind === "briefing") {
        if (!fromArena) {
          const why = trustedSender(event, arena).reason;
          const whySelf = selfDomain ? trustedSender(event, `arena-test@${selfDomain}`).reason : "no recipient";
          return skip(`untrusted-arena-mail from ${email.sender?.address ?? "?"} (arena check: ${why}; test sender check: ${whySelf})`);
        }
      }

      if (kind === "start") {
        const g = parseGameBlock(email.text);
        await save({ ...(await load()), game, civ: g?.civ, arena, mailboxes: g?.mailboxes ?? {}, status: "live" });
        return Response.json({ ok: true, game, stored: "start" });
      }
      if (kind === "over") {
        await save({ ...(await load()), status: "over", outcome: parseGameOver(email.text) });
        return Response.json({ ok: true, game, stored: "over" });
      }

      if (kind === "letter") {
        // Only a mailbox the arena listed for this game may write to us.
        const state = await load();
        const sender = extractEmailAddresses(event.email.headers.from)[0] ?? "";
        const fromCiv = civOfSender(state.mailboxes, sender);
        if (!fromCiv || sender === self) return skip(`letter from ${sender || "?"}, not a mailbox in game ${game}`);
        const auth = trustedSender(event, sender);
        if (!auth.trusted) return skip(`letter claiming to be ${fromCiv} failed authentication (${auth.reason})`);
        const inbox = [...(state.inbox ?? []), { fromCiv, text: (email.text ?? "").slice(0, 4000), turn: state.lastTurn }].slice(-10);
        await save({ ...state, inbox });
        const answer = await onLetter({ game, fromCiv, text: email.text ?? "", subject: email.subject }, env, state);
        if (answer && state.civ) {
          const reply = await client.reply(email, { text: answer });
          await client.send({
            from: self, to: state.arena ?? arena,
            subject: letterSubject(game, state.civ, fromCiv), bodyText: answer,
          }).catch((e) => console.error("arena copy failed:", e));
          return Response.json({ ok: true, reply });
        }
        return Response.json({ ok: true, game, letter: "read" });
      }

      // A turn briefing: refresh what we know about the game, decide, reply.
      const state = await load();
      const civ = /^(.+?) turn (\d+)\s*$/i.exec(parseSubject(email.subject).rest);
      const next: GameState = {
        ...state, game, arena, status: "live",
        civ: civ?.[1] ?? state.civ,
        lastTurn: civ ? Number(civ[2]) : state.lastTurn,
        mailboxes: parseMailboxes(email.text) ?? state.mailboxes ?? {},
      };
      const text = await decide(email.text ?? "", env, next);
      const reply = await client.reply(email, { text });
      await save({ ...next, inbox: [] }); // letters were in front of decide() this turn

      // Letters: <DIPLOMACY to="Greece">...</DIPLOMACY> blocks in the reply go
      // to that civ's mailbox, with a copy to the arena for the game record.
      for (const letter of extractLetters(text).slice(0, 3)) {
        const to = mailboxFor(next.mailboxes, letter.to);
        if (!to || to.address === self || !next.civ) continue;
        const subject = letterSubject(game, next.civ, to.civ);
        await client.send({ from: self, to: to.address, subject, bodyText: letter.text }).catch((e) => console.error("letter failed:", e));
        await client.send({ from: self, to: arena, subject, bodyText: letter.text }).catch((e) => console.error("arena copy failed:", e));
      }

      return Response.json({ ok: true, reply });
    } catch (err) {
      // Return 2xx so the webhook delivery loop does not retry a bug
      // it cannot fix. The function-invocation row still records the
      // error body for debugging. Flip to a 5xx status if you want
      // transient failures retried (e.g. a flaky external API you call).
      console.error("handler error:", err);
      return Response.json(
        { ok: false, error: err instanceof Error ? err.message : String(err) },
        { status: 200 },
      );
    }
  },
};
