// A primitive civ agent as a Primitive Function. Each turn the arena emails
// this address a briefing; this handler replies in thread with orders chosen
// by decide() in src/agent.mjs. Everything except the civ-specific part below
// comes from the Primitive "email-reply" Function template.
//
// env.PRIMITIVE_API_KEY, env.PRIMITIVE_WEBHOOK_SECRET, and
// env.PRIMITIVE_API_BASE_URL are auto-injected by the Primitive Functions runtime.
// Optional secret: ANTHROPIC_API_KEY (and MODEL) to let a model play.
//
// Imports are taken from the `/api` subpath, NOT the package root.
// The root export pulls in webhook signing helpers that depend on
// `node:crypto`, which breaks Workers-style bundles. The `/api`
// subpath is Workers-safe and exposes everything a handler needs,
// including Web Crypto signature verification.
import {
  createPrimitiveClient,
  normalizeReceivedEmail,
  PRIMITIVE_SIGNATURE_HEADER,
  type EmailReceivedEvent,
  verifyWebhookSignature,
  WebhookVerificationError,
} from "@primitivedotdev/sdk/api";
// @ts-expect-error plain ESM module
import { decide } from "./src/agent.mjs";

interface Env {
  PRIMITIVE_API_KEY: string;
  PRIMITIVE_API_BASE_URL: string;
  PRIMITIVE_WEBHOOK_SECRET: string;
  ANTHROPIC_API_KEY?: string;
  MODEL?: string;
}

// Turn briefings (games and the sign-up example turn) have subjects like
// "primitive civ [<game-id>]: Rome turn 12". Anything else is ignored,
// including "Re: ..." replies, so the agent never answers its own mail.
const BRIEFING_SUBJECT = /^\s*primitive civ \[[^\]]+\]: .+ turn \d+/i;

// Optional loop-protection knob. client.reply() server-defaults the
// outbound from-address from the inbound recipient, so most handlers
// do not need to fill this in. Add any extra addresses your handler
// sends from if you later switch to client.send or a custom domain.
const EXTRA_SELF_ADDRESSES: string[] = [
  // "bot@your-domain.example",
];

function extractEmailAddresses(value: string | null | undefined): string[] {
  return (
    value?.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)?.map((address) =>
      address.toLowerCase(),
    ) ?? []
  );
}

function domainPart(address: string): string | null {
  const at = address.lastIndexOf("@");
  return at === -1 ? null : address.slice(at + 1).toLowerCase();
}

function localPart(address: string): string {
  const at = address.lastIndexOf("@");
  return at === -1 ? address.toLowerCase() : address.slice(0, at).toLowerCase();
}

function inboundRecipientAddresses(event: EmailReceivedEvent): string[] {
  return [
    ...event.email.smtp.rcpt_to.flatMap(extractEmailAddresses),
    ...extractEmailAddresses(event.email.headers.to),
  ];
}

function inboundRecipientDomains(event: EmailReceivedEvent): Set<string> {
  return new Set(
    inboundRecipientAddresses(event)
      .map(domainPart)
      .filter((domain): domain is string => domain !== null),
  );
}

// Loop protection. A newly deployed Function starts as a fallback
// endpoint for managed domains and can receive bounces or auto-replies
// generated by its own outbound mail. Do not hardcode a managed suffix:
// staging, production, and custom domains all arrive through the same
// webhook shape. Derive the handler's inbound domains from the actual
// SMTP recipients instead.
//
// The default check skips:
//   - bounce notifications, which RFC 5321 requires to use an empty
//     SMTP envelope sender (MAIL FROM:<>). Replying to a null sender
//     is forbidden and would itself bounce, producing a
//     bounce-of-bounce chain. The body header on a bounce typically
//     reads "From: MAILER-DAEMON@..." which a naive From-only check
//     would treat as a normal sender, so we gate on the envelope here.
//   - direct self-mail where From equals one of the inbound recipients;
//   - mailer-daemon/postmaster bounces from the same domain as the
//     inbound, as a backup for bounces that arrive with a non-empty
//     envelope sender;
//   - any address explicitly listed in EXTRA_SELF_ADDRESSES.
//
// Anything with no identifiable sender at all (envelope + From both
// empty) is treated as a loop terminator: better to drop one ambiguous
// message than to reply blindly and loop on a bounce.
//
// Extend this helper if you need stricter detection. Common additions
// not implemented here today:
//   - Honor RFC 3834 auto-response headers: skip when an
//     auto-submitted header is anything other than "no", or when a
//     list-unsubscribe / precedence: bulk header is present. The
//     EmailReceivedEvent.email.headers shape does not currently surface
//     these, so detection requires either a parsed-headers field on
//     the event or a parse of the raw RFC 822 body.
//   - Track Message-ID / In-Reply-To chains to break ping-pong loops
//     between two cooperating handlers on different domains.
//   - Rate-limit replies per sender per hour as a safety net.
//
// Loop protection is NOT sender authentication. The address matching
// here is deliberately loose (it exists to avoid replying to our own
// mail, where a false positive just drops one reply). If your handler
// gates any privileged action on WHO sent the email, do not reuse this
// logic or regex the From header yourself; use isTrustedSender from
// "@primitivedotdev/sdk/api", which anchors the DMARC verdict to your
// expected domain and strict-parses the From header.
export function isLoop(event: EmailReceivedEvent): boolean {
  // RFC 5321: bounce notifications use the null MAIL FROM (envelope
  // sender = empty string). Some MTAs report this as "<>" verbatim.
  // Treat either as an unambiguous bounce signal.
  const envelopeSender = (event.email.smtp.mail_from || "").trim();
  if (envelopeSender === "" || envelopeSender === "<>") return true;

  const fromAddresses = [
    ...extractEmailAddresses(event.email.headers.from),
    ...extractEmailAddresses(event.email.smtp.mail_from),
  ];
  // No identifiable sender across either envelope or header: treat as
  // a loop terminator. Was return false in the original template; that
  // returned mail with empty headers straight back into the handler
  // and let bounces with malformed bodies slip past the bounce guard
  // above.
  if (fromAddresses.length === 0) return true;

  const inboundAddresses = new Set(inboundRecipientAddresses(event));
  const inboundDomains = inboundRecipientDomains(event);
  const extraSelfAddresses = new Set(
    EXTRA_SELF_ADDRESSES.map((address) => address.toLowerCase()),
  );

  for (const from of fromAddresses) {
    if (inboundAddresses.has(from)) return true;
    if (extraSelfAddresses.has(from)) return true;

    const fromDomain = domainPart(from);
    const fromLocal = localPart(from);
    const sameInboundDomain = fromDomain ? inboundDomains.has(fromDomain) : false;
    if (
      sameInboundDomain &&
      (fromLocal === "mailer-daemon" || fromLocal === "postmaster")
    ) {
      return true;
    }
  }

  return false;
}

export default {
  async fetch(
    req: Request,
    env: Env,
  ): Promise<Response> {
    try {
      const rawBody = await req.text();
      const signatureHeader = req.headers.get(PRIMITIVE_SIGNATURE_HEADER) ?? "";

      try {
        await verifyWebhookSignature({
          rawBody,
          signatureHeader,
          secret: env.PRIMITIVE_WEBHOOK_SECRET,
        });
      } catch (signatureError) {
        if (signatureError instanceof WebhookVerificationError) {
          return new Response("invalid signature", { status: 401 });
        }
        throw signatureError;
      }

      const event = JSON.parse(rawBody) as EmailReceivedEvent;

      // Only "email.received" exists today. Future event types will
      // arrive with a different discriminator; return 2xx so the
      // delivery loop does not burn its retry budget on payloads you
      // intentionally skipped.
      if (event.event !== "email.received") {
        return Response.json({ ok: true, skipped: event.event });
      }

      // Loop protection runs immediately after signature verification
      // and the event-type check. See isLoop above for what's covered
      // and how to extend it.
      if (isLoop(event)) {
        return Response.json({ ok: true, skipped: "loop" });
      }

      const client = createPrimitiveClient({
        apiKey: env.PRIMITIVE_API_KEY,
        apiBaseUrl: env.PRIMITIVE_API_BASE_URL,
      });

      const email = normalizeReceivedEmail(event);
      if (!BRIEFING_SUBJECT.test(email.subject ?? "")) {
        return Response.json({ ok: true, skipped: "not-a-briefing" });
      }

      // The briefing is the email body. decide() returns the whole reply:
      // a line of reasoning and one <ORDERS>[...]</ORDERS> block. Reply in
      // thread (client.reply) so the arena can match it to the turn.
      const text = await decide(email.text ?? "", env);
      const reply = await client.reply(email, { text });
      return Response.json({ ok: true, reply });
    } catch (err) {
      // Return 2xx so the webhook delivery loop does not retry a bug
      // it cannot fix. The function-invocation row still records the
      // error body for debugging. Flip to a 5xx status if you want
      // transient failures retried (e.g. a flaky external API you call).
      console.error("handler error:", err);
      return Response.json(
        { ok: false, error: err instanceof Error ? err.message : String(err) },
        { status: 200 },
      );
    }
  },
};
